In [54]:
import numpy as np

n = [5, 10, 20, 30, 50]

A1 = np.array([[1/4, 3/4, 0, 0], [1/2, 0, 1/2, 0], [0, 1/2, 0, 1/2], [0, 0, 3/4, 1/4]])

A2 = np.array([[2/9, 1/3, 0, 4/9], [4/9, 1/9, 0, 4/9], [2/9, 2/9, 2/9, 1/3], [2/9, 2/9, 4/9,1/9]])

A3 = np.array([[4/9, 0, 2/9, 1/3], [0, 4/9, 2/9, 1/3], [0, 2/3, 0, 1/3], [4/9, 2/9, 2/9, 1/9]])

def stationary_distribution(A, k):
    n = np.shape(A)[1]
    v0 = np.zeros(n-1)
    v0 = np.append(v0,1)
    v1 = np.ones(n-1)
    v1 = np.append(v1,2)
    A1 = np.delete(A2, n-1, axis = 0)
    M1 = np.vstack((A1, v1)) - np.eye(n)
    solve = np.linalg.solve(M1, v0)
    print("Стационарное распределние матрицы A", k,':', solve)

def power(A, n, k):
    for i in n:
        l = np.linalg.matrix_power(A, i)
        print('Матрица A',k ,'в степени', i, ':')
        print(l, '\n')


print(stationary_distribution(A1,1),'\n')
print(stationary_distribution(A2, 2),'\n')
print(stationary_distribution(A3, 3),'\n')


print(power(A1, n, 1))
print(power(A2, n, 2))
print(power(A3, n, 3))

Стационарное распределние матрицы A 1 : [0.25 0.25 0.25 0.25]
None 

Стационарное распределние матрицы A 2 : [0.25 0.25 0.25 0.25]
None 

Стационарное распределние матрицы A 3 : [0.25 0.25 0.25 0.25]
None 

Матрица A 1 в степени 5 :
[[0.17675781 0.43066406 0.16992188 0.22265625]
 [0.28710938 0.14648438 0.453125   0.11328125]
 [0.11328125 0.453125   0.14648438 0.28710938]
 [0.22265625 0.16992188 0.43066406 0.17675781]] 

Матрица A 1 в степени 10 :
[[0.22371578 0.25403881 0.34596062 0.17628479]
 [0.16935921 0.36967659 0.23032379 0.23064041]
 [0.23064041 0.23032379 0.36967659 0.16935921]
 [0.17628479 0.34596062 0.25403881 0.22371578]] 

Матрица A 1 в степени 20 :
[[0.20394139 0.29141525 0.30858475 0.19605861]
 [0.19427683 0.31252614 0.28747386 0.20572317]
 [0.20572317 0.28747386 0.31252614 0.19427683]
 [0.19605861 0.30858475 0.29141525 0.20394139]] 

Матрица A 1 в степени 30 :
[[0.20071303 0.29844139 0.30155861 0.19928697]
 [0.19896093 0.30227164 0.29772836 0.20103907]
 [0.20103907 0.2977